site_name: Aipress24 doc

docs_dir: src

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book-open-page-variant
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant


extra:
  # homepage: https://nua.rocks
  # generator: false
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/abilian/nua
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/abilianhq
  analytics:
    provider: custom


# Extensions
markdown_extensions:
  - meta
  - footnotes
  - toc:
      permalink: true
  - smarty
  - sane_lists
  - nl2br
  - fenced_code
  - pymdownx.magiclink
  - pymdownx.tasklist
  # - pymdownx.superfences

plugins:
  - search
  - roamlinks
#  - with-pdf:
#      author: Stefane Fermigier / Erick Haensen / ...
#      copyright: © 2022-2024 Agence TCA (user doc) & Abilian (tech doc)
#      cover: true
#      back_cover: false
#      cover_title: AIpress24
#      cover_subtitle: La platforme du journalisme 3.0
#      enabled_if_env: ENABLE_PDF_EXPORT
#
#      #    custom_template_path: TEMPLATES PATH
#      #
#      #toc_title: TOC TITLE TEXT
#      #heading_shift: false
#      #toc_level: 3
#      #ordered_chapter_level: 2
#      #excludes_children:
#      #    - 'release-notes/:upgrading'
#      #    - 'release-notes/:changelog'
#      #
#      #exclude_pages:
#      #    - 'bugs/'
#      #    - 'appendix/contribute/'
#      #convert_iframe:
#      #    - src: IFRAME SRC
#      #      img: POSTER IMAGE URL
#      #      text: ALTERNATE TEXT
#      #    - src: ...
#      #two_columns_level: 3
#      #
#      #render_js: true
#      #headless_chrome_path: headless-chromium
#      #
#      #output_path: any-place/document.pdf
#      #
#      #debug_html: true
#      #show_anchors: true
#      #verbose: true
#  - mkdocstrings:
#      default_handler: python
#      handlers:
#        python:
#          rendering:
#            show_source: false
#      custom_templates: templates
#      watch:
#        - ../src/app

nav:
  - Home: index.md
  - Utilisateurs:
      - Intro: user/index.md
  - Developers:
      - Intro: dev/index.md
      - Architecture: dev/architecture.md
      - Modules: dev/modules.md
      - Services: dev/services.md
      - Database: dev/database.md
      - API (back-end): dev/api.md
      - Open Source Librairies: dev/libraries.md
      - Front-End: dev/front-end.md
      - Misc. Notes: dev/notes.md
      - Dolibarr Integration: dev/dolibarr.md
      - Glossary: dev/glossary.md
      - Tests: dev/tests.md
