#!/usr/bin/env python3
"""Pull the AIpress24 OpenAPI spec into the docs and stamp it for publishing.

The canonical spec is generated by the application repository
(``aipress24/sdk/python/openapi.json`` via ``make api-sdk`` there) and kept
origin-agnostic (no ``servers`` block, so the app's own ``/api/v1/docs`` works
against whatever host it is served from). For the *published* documentation we
add a ``servers`` entry pointing at production, so the Swagger UI "Try it out"
button targets the real API.

Usage::

    python3 scripts/build_openapi.py [path/to/openapi.json]

Defaults to ``../aipress24/sdk/python/openapi.json`` (the sibling app checkout).
The result is written to ``src/dev/api-explorer/openapi.json`` and committed, so
the site also builds where the app repo is not available (CI, deploy host).
"""

from __future__ import annotations

import json
import pathlib
import sys

DEFAULT_SRC = pathlib.Path("../aipress24/sdk/python/openapi.json")
DST = pathlib.Path("src/dev/api-explorer/openapi.json")
SERVERS = [{"url": "https://aipress24.com", "description": "Production"}]

# Subdomain groups, in the order Swagger UI / ReDoc should render them. The app
# registers everything on one blueprint (one flat tag), so we re-tag operations
# by path here — a presentation concern that belongs with publishing, and one
# every OpenAPI renderer honours.
TAGS: list[tuple[str, str]] = [
    ("Discovery", "The API entry point and its link relations."),
    ("Content", "Published articles, press releases and events (public, read)."),
    ("Organisations", "Active organisations and Business Walls (read)."),
    ("Directory", "Public member profiles (read)."),
    (
        "My content",
        "The token owner's own profile, articles, press releases, events and "
        "enquiry notices — read, plus authoring and publishing.",
    ),
    (
        "My marketplace",
        "The token owner's own missions, projects, jobs and products (read).",
    ),
]
_MARKETPLACE = {"missions", "projects", "jobs", "products"}
_CONTENT = {"articles", "press-releases", "events"}
_ORGS = {"organisations", "business-walls"}
_HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def _tag_for(path: str) -> str:
    """Map an ``/api/v1/…`` path to its subdomain tag."""
    rest = path.removeprefix("/api/v1").strip("/")
    if not rest:
        return "Discovery"
    segments = rest.split("/")
    head = segments[0]
    if head == "me":
        if len(segments) >= 2 and segments[1] in _MARKETPLACE:
            return "My marketplace"
        return "My content"
    if head in _CONTENT:
        return "Content"
    if head in _ORGS:
        return "Organisations"
    if head == "members":
        return "Directory"
    return "Content"  # sensible default for any new content-like path


def _regroup(spec: dict) -> None:
    """Assign each operation a single subdomain tag and order the tag sections."""
    for path, item in spec.get("paths", {}).items():
        tag = _tag_for(path)
        for method, operation in item.items():
            if method in _HTTP_METHODS and isinstance(operation, dict):
                operation["tags"] = [tag]
    spec["tags"] = [{"name": name, "description": desc} for name, desc in TAGS]


def main() -> int:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.is_file():
        print(f"error: OpenAPI source not found: {src}", file=sys.stderr)
        return 1

    spec = json.loads(src.read_text(encoding="utf-8"))
    spec["servers"] = SERVERS
    _regroup(spec)

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    groups = ", ".join(name for name, _ in TAGS)
    print(f"wrote {DST} ({len(spec.get('paths', {}))} paths) from {src}")
    print(f"grouped into: {groups}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
